### ISSUE TITLE
Ability to see code in the storybook guide 

### ISSUE THREAD

**Issue by gmontgom-it** [patrickcate/vue-uswds#663]
It would be nice to have the ability to see the code associated with each component in the story book guide. I have seen this in other apps like https://storybook.ui.scaleway.com/?path=/docs/components-feedback-alert--docs see: 
![image](https://github.com/patrickcate/vue-uswds/assets/54565251/18511784-c002-4beb-8b4d-3b0f34c9beb4)

Thanks so much for this awesome project and your hard work on this!

**Comment by patrickcate** [comment]
As part of the storybook 8 upgrade code examples have been added.
